<center><h1> CPE 4040 Spring 2023: Homework 3</h1></center>

1. Write your answer in the cell provided under each question.
2. __Important: Write comments__ in the code to explain your thoughts. __You may lose points without comments.__
3. Show your execution result. 
4. Do your own work. __Do not copy and paste other people's (or AI's) codes.__    

### Submission:
 * __Submit this notebook file and the pdf version__ - remember to add your name in the filename.
 * Deadline: 11:59 pm, 2/15 (Wednesday)

### Q1: Functions and Lambda (10 Points)

Q1.1: Use the sorted( ) function to sort the tuples in the list based on the second item (that is, the state name), in ascending order alphabetically. You will write a small function, "second", to achieve this purpose. 

In [1]:
state=[(19542209, "New York") ,(4887871, "Alabama"), (1420491, "Hawaii"), 
       (626299, "Vermont"), (1805832, "West Virginia"), (39865590, "California")]

In [2]:
def second(item):
    return item[1]  

sortedState = sorted(state, key=second)

print(sortedState)

[(4887871, 'Alabama'), (39865590, 'California'), (1420491, 'Hawaii'), (19542209, 'New York'), (626299, 'Vermont'), (1805832, 'West Virginia')]


Q1.2 Perform the same task as in Q1.1, however, you will write a lambda function to replace "second". 

In [3]:
sortedState = sorted(state, key=lambda item: item[1])

print(sortedState)

[(4887871, 'Alabama'), (39865590, 'California'), (1420491, 'Hawaii'), (19542209, 'New York'), (626299, 'Vermont'), (1805832, 'West Virginia')]


Q1.3 Use the sorted( ) function and lambda to sort the tuples in the list based on the __last character of the second items.__

In [4]:
sortedState = sorted(state, key=lambda item: item[1][-1])

print(sortedState)

[(4887871, 'Alabama'), (1805832, 'West Virginia'), (39865590, 'California'), (1420491, 'Hawaii'), (19542209, 'New York'), (626299, 'Vermont')]


### Q2: List Comprehension vs. Map/Filter + Lambda (15 Points)
For each question below, use both list comprehension and Python map( ) or filter( ) function. Use __%%timeit__ magic command to profile the computation time. Make some comments about the profiling results.

#### Q2.1 For each of the floating number in the list, calcuate the __square__ of it and __round__ the result to 2 decimal places. 

In [5]:
num = [4.35, 6.09, 3.25, 9.77, 2.16, 8.88, 4.59]

In [6]:
# Use List Comprehension first
squares = [round(x**2, 2) for x in num]

print(squares)

[18.92, 37.09, 10.56, 95.45, 4.67, 78.85, 21.07]


In [7]:
# Use map() function
squares = list(map(lambda x: round(x**2, 2), num))

print(squares)

[18.92, 37.09, 10.56, 95.45, 4.67, 78.85, 21.07]


In [8]:
%%timeit 
## Profile the computation time for both methods
#list comprehension
squares = [round(x**2, 2) for x in num]

3.74 µs ± 66.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%%timeit
#Map Function
squares = list(map(lambda x: round(x**2, 2), num))

4.36 µs ± 54.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Q2.2 For each of the name in the list, print only the names with less than 7 letters.

In [10]:
names = ["olumide", "akinremi", "alex", "josiah", "john", "temidayo", "emily", "omoseun"]

In [11]:
# Use List Comprehension first
lessThanSeven = [name for name in names if len(name) < 7]

print(lessThanSeven)

['alex', 'josiah', 'john', 'emily']


In [12]:
# Use filter() function

filterSeven = list(filter(lambda name: len(name) < 7, names))

print(filterSeven)

['alex', 'josiah', 'john', 'emily']


In [13]:
%%timeit
## Profile the computation time for both methods
#List Comprehension
lessThanSeven = [name for name in names if len(name) < 7]

461 ns ± 6.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
%%timeit
#filter function
filterSeven = list(filter(lambda name: len(name) < 7, names))

939 ns ± 5.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Q3: Dictionary Operations (20 Points)

#### Q3.1 Nested Dictionary
KSU wants to create a dictionary for each class to hold the following faculty and student information:
   * for faculty: name only
   * for each student: 1. name, 2. grades for two assignments: Homework and Midterm
    
Dr. Yiin teaches a class with 2 students (really great faculty/student ratio!), but he needs your help to construct a Python directory. Please finish what he started below.

Use the following information for student 1 and 2.
   * Student 1: name: Kramer, grades: homework 90, midterm 80
   * Student 2: name: Kelly, grades: homework 96, midterm 87

Print out the following information:
   1. The Mid-term grade of Cramer
   2. The names of the two students  

In [15]:
classroom = {
    'faculty': 'Dr. Yiin',
    'students': [ 
        {   'name': 'Kramer',
            'grades': {
                'homework': 90,
                'midterm': 80}},
        {   'name': 'Kelly',
            'grades': {
                'homework': 96,
                'midterm': 87 }}
        ]}

print("Kramer's Mid Term Score:", classroom['students'][0]['grades']['midterm'])


print("Students in the Class:")
for student in classroom['students']:
    print(student['name'])

Kramer's Mid Term Score: 80
Students in the Class:
Kramer
Kelly


#### Q3.2 Shopping Lists
You are given two shopping lists (with items and quantity), one from your mom and one for yourself:
 * mom's list: banana 5, avacodo 8, eggs 12, milk 2, orange 6
 * your list: Red Bull 12, potato chips 5, pineapple 3, eggs 6, avacodo 4
        
Please construct two dictionaries, one for each shopping list.

In [16]:
momList = {
    'banana': 5,
    'avocado': 8,
    'eggs': 12,
    'milk': 2,
    'orange': 6
}

myList = {
    'Red Bull': 12,
    'potato chips': 5,
    'pineapple': 3,
    'eggs': 6,
    'avocado': 4
}

#### Q3.3 Merging the Shopping Lists
You realize there are some overlapping items on the lists, so you decide to merge the two.

Please write a __function, merge_shop_list(a, b)__, that takes two dictionaries a and b as inputs, and merge them together. If there is a common item, you should add the quantities together. The function shall return the merged dictionary (or the shopping list).

Show your result by printing the merged shopping list.

In [17]:
"""
update() does not work as it only will merge the two lists together without changing the quanity number
With the use logic and accessing the items in a for loop, we can
merge the list and update quanities at the same time.
"""
def merge_shop_list(a, b):
    result = a
    for item, quantity in b.items():
        if item in result:
            result[item] += quantity  
        else:
            result[item] = quantity  
    return result

shoppingList = merge_shop_list(momList, myList)
print(shoppingList)

{'banana': 5, 'avocado': 12, 'eggs': 18, 'milk': 2, 'orange': 6, 'Red Bull': 12, 'potato chips': 5, 'pineapple': 3}


### Q4: AppleStore Dataset (30 points)

#### Q4.1 Genres and Content Ratings

With the AppleStore dataset, we found that "Game" is the most popular genre with more than 3000+ apps. We also realized that there are four different age-based content ratings (4+, 9+, 12+, and 17+). 

Write a Python program that analyzes the content rating distribution for the top three genres (Game, Entertainment and Education). That is, we want to know, for example, in the "Game" genere, how many apps are 4+, 9+, 12+, and 17+, respectively. 

There are different ways to do this. Try your best to come up with a solution. 

In [18]:
opened_file = open('AppleStore.csv', encoding="utf-8")
from csv import reader

read_file = reader(opened_file)
apps_data = list(read_file)

In [19]:
#This will store the dictionary and count how many games total are there in the genre
genre_counting = {}
game_genre = 0
entertain_genre = 0
education_genre = 0

#Keeps up with the Games category age rating
gameFourPlusCount = 0
gameNinePlusCount = 0
gameTwelvePlusCount = 0
gameSeventeenPlusCount = 0

#Keeps up with the Entertainment category age rating
entertainFourPlusCount = 0
entertainNinePlusCount = 0
entertainTwelvePlusCount = 0
entertainSeventeenPlusCount = 0

#Keeps up with the Education category age rating
eduFourPlusCount = 0
eduNinePlusCount = 0
eduTwelvePlusCount = 0
eduSeventeenPlusCount = 0

#This is used to help the if statements pass through as an else statement is required.
passelse = 0

"""
Will go through the CSV file and check the genre the app is in.
If it is a Game, Entertainment, or Education app, it will go to the rating row and
Check to see the age rating and update the app total and age rating count 
"""
for row in apps_data[1:]:
    genre = row[11]
    if genre in genre_counting.keys():
       if genre == 'Games':
            rating = row[10]
            if rating == '4+':
                 gameFourPlusCount += 1    
            elif rating == '9+':
                gameNinePlusCount += 1
            elif rating == '12+':
                gameTwelvePlusCount += 1
            elif rating == '17+':
                gameSeventeenPlusCount += 1
            else:
                passelse = 0 
            game_genre += 1
       elif genre == 'Entertainment':
            rating = row[10]
            if rating == '4+':
                 entertainFourPlusCount += 1    
            elif rating == '9+':
                entertainNinePlusCount += 1
            elif rating == '12+':
                entertainTwelvePlusCount += 1
            elif rating == '17+':
                entertainSeventeenPlusCount += 1
            else:
                passelse = 0 
            entertain_genre += 1
       elif genre == 'Education':
            if rating == '4+':
                eduFourPlusCount += 1    
            elif rating == '9+':
                eduNinePlusCount += 1
            elif rating == '12+':
                eduTwelvePlusCount += 1
            elif rating == '17+':
                eduSeventeenPlusCount += 1
            else:
                passelse = 0 
            education_genre += 1
    else:
        genre_counting[genre] = 1
    
#Prints out all that has been counted in the loop in sepreate categories
print('Total Games:',game_genre)
print('4+:',gameFourPlusCount)
print('9+:',gameNinePlusCount)
print('12+:',gameTwelvePlusCount)
print('17+:',gameSeventeenPlusCount)

print('Total Entertainment Apps:',entertain_genre)
print('4+:',entertainFourPlusCount)
print('9+:',entertainNinePlusCount)
print('12+:',entertainTwelvePlusCount)
print('17+:',entertainSeventeenPlusCount)

print('Total Education Apps:',education_genre)
print('4+:',eduFourPlusCount)
print('9+:',eduNinePlusCount)
print('12+:',eduTwelvePlusCount)
print('17+:',eduSeventeenPlusCount)

Total Games: 3861
4+: 2079
9+: 864
12+: 741
17+: 177
Total Entertainment Apps: 534
4+: 284
9+: 44
12+: 108
17+: 98
Total Education Apps: 452
4+: 256
9+: 83
12+: 83
17+: 30


__Q4.2 We are also interested in the price of the apps. Specifically, we want to know the number of applications in five different price ranges, that is,__ 
1. free
2. 0 < price < 5
3. 5<= price < 10
4. 10 <= price < 50
5. price >=50.

Please write a code that shows the price range distribution.

In [20]:
# Initialize the price range dictionary. You will write the rest.

price_range = {'Free': 0, '0 to $5': 0, '$5 to $10': 0, '$10 to $50': 0, '>= $50': 0}


In [21]:
#Creates an empty dictionary
price_counting = {}

#Creates counts for us to update the dictionary later
freeCount = 0
zeroTo5Count = 0
fiveTo10Count = 0
tenTo50Count = 0
greaterThan50Count = 0

"""
The for loop will go through each row of the prices. Conidering that the program reads the CSV as a string,
we have to conver the row to interger floating values to read and compare what is in the column.
"""
for row in apps_data[1:]:
    price = int(float(row[4]))
    if price in price_counting.keys():
        if price == 0:
            freeCount += 1
        elif price > 0 and price < 5:
            zeroTo5Count += 1
        elif price >=5 and price < 10:
            fiveTo10Count += 1
        elif price >= 10 and price < 50:
            tenTo50Count += 1
        elif price >= 50:
            greaterThan50Count += 1
        else:
            passelse = 0
    else:
        price_counting[price] = 1     

#Will Update the Dictionary with the newly found values.        
updatedValues = {'Free': freeCount, '0 to $5': zeroTo5Count, '$5 to $10': fiveTo10Count, '$10 to $50': tenTo50Count, '>= $50': greaterThan50Count}
price_range.update(updatedValues)
print(price_range)

{'Free': 4783, '0 to $5': 1971, '$5 to $10': 336, '$10 to $50': 70, '>= $50': 2}


<h3>Q5: Checker Board (10 Points)</h3>

In [22]:
"""
With the use of numpy functions, the first three rows repeat themselves for rows 5-9, so
by shifting and putting the three rows into the 9x9 array. We can use this pattern to print it three more times
and by doing that we have created the array above.
"""
import numpy as np

ninebynine = np.zeros((9,9))

for i in range(3):
    array = [1, 0, 0, 1, 0, 0, 1, 0, 0]
    print(array)
    lastelement = array[-1]
    for i in range(2):
        ninebynine[i:] = array
        for i in range(len(array)-1, 0, -1):
                    array[i] = array[i-1]
        array[0] = lastelement
        print(array)


[1, 0, 0, 1, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 1, 0, 0, 1, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 1]
[1, 0, 0, 1, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 1, 0, 0, 1, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 1]
[1, 0, 0, 1, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 1, 0, 0, 1, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 1]


<h3>Q6: Array Indexing and Slicing (15 Points) </h3>

1. Please convert this vector, np.arange(48), into a 8x6 array, i.e, 8 rows and 6 columns. Let's call this array A.

2. Write codes to extract the elements in columns 2, 3, and 5 from A.

3. Create a new 3x5 array, with elements from rows 6, 1, 3 of A (in that order). Hint: use fancy indexing

4. Write codes to extract four elements from A with the following indices (4,2), (5,0), (1,2), (3,3).

In [23]:
A = np.arange(48)

print('\nNumber One:')
A_Reshape = np.reshape(A, (8, 6))
print(A_Reshape)

columns = [2, 3, 5]
columnExtraction = A_Reshape[:, columns]

print('\nNumber Two:')
print(columnExtraction)

rows = [6, 1, 3]

threeByFive = A_Reshape[rows, :5]

print('\nNumber Three:')
print(threeByFive)

indexNumber = [(4, 2), (5, 0), (1, 2), (3, 3)]
elements = A_Reshape[[i[0] for i in indexNumber], [i[1] for i in indexNumber]]

print('\nNumber Four:')
print(elements)


Number One:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]

Number Two:
[[ 2  3  5]
 [ 8  9 11]
 [14 15 17]
 [20 21 23]
 [26 27 29]
 [32 33 35]
 [38 39 41]
 [44 45 47]]

Number Three:
[[36 37 38 39 40]
 [ 6  7  8  9 10]
 [18 19 20 21 22]]

Number Four:
[26 30  8 21]
